### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by xen-42** [2walker2/Astral-Codex#1]
![image](https://github.com/2walker2/Astral-Codex/assets/22628069/fcd670af-2ece-460a-b4e6-b769f11cb31b)

Should be "can to make sure"

Yoinked this pic from etherpod but saw it too just forgot to screencap

![image](https://github.com/2walker2/Astral-Codex/assets/22628069/f57412d8-29d3-422c-9e7e-42f2a8d0221f)

Should just be "there" or "that there" ig

**Comment by 2walker2** [comment]
Thanks for letting me know. Just fixed.
