### ISSUE TITLE
Inconsistency between the ship log picture and the actual thing on Ash Twin

### ISSUE THREAD

**Issue by TRSasasusu** [2walker2/Astral-Codex#10]
The ship log shows the scroll is stored in the shelf:
![スクリーンショット (4515)](https://github.com/2walker2/Astral-Codex/assets/17728957/89207f61-0106-4a30-bb53-035b477a4516)

But, actually, it is on the ground:
![スクリーンショット (4524)](https://github.com/2walker2/Astral-Codex/assets/17728957/79f4ea08-88fe-4445-a954-6c461a33d9c5)

(I know this inconsistency occurs in the recent patches.)

**Comment by 2walker2** [comment]
The scroll (and its ship logs) have been removed entirely since they were causing confusion more than they were serving as a helpful hint.
