### ISSUE TITLE
Request for translate

### ISSUE THREAD

**Issue by JenkoSII** [2walker2/Astral-Codex#15]
Hi, I'm a French Outer Wilds player and I love playing absolutely amazing mods so I was looking for some good mods and saw your mod; Astral codec. This mod is crazy and the music is really amazing but the reading comprehension part was a bit difficult for me so I had an idea. I would like to help translate it into French for the next French players who play this mod. It will be easier for them to understand the story and solve the puzzles. If you were already planning to translate the mod, then thank you. And I want to know how to contact you if you need help translating.

Thanks, Jenko.

**Comment by 2walker2** [comment]
Hello,
I'm glad you enjoyed the mod! There is a French translation in progress but the person handling it has been busy lately so it's been going pretty slowly. If you're interested in helping out that would be fantastic. Just ping me on the Outer Wilds modding Discord server (@2walker2) and I can add you to the translation group chat.
