### ISSUE TITLE
Readme cypher - markdown interpretation issue

### ISSUE THREAD

**Issue by YanWittmann** [2walker2/Astral-Codex#3]
Really, nothing major, but I just tried to translate the text from the readme:

```md
@;{&< ?/ })& ?]["[/;| ?/&+} (?] &?}&
```

but got:

```
based on the original onept for eote
```

Meaning, the "c"s got lost. This is because the "*" characters are interpreted as mardown bold formatting symbols.

To solve this, replace the contents with this:

```md
# Astral Codec

A story mod exploring the origin of The Interloper. @;{&< ?/ })& ?]["[/;| \*?/\*&+} (?] &?}&  
[Trailer](https://www.youtube.com/watch?v=4C9uYPns-0w)

![thumbnailMBGNAG](https://github.com/2walker2/Astral-Codex/assets/48959058/3f6278ef-12a8-45e8-a422-db03641c3021)
```

(also note that I added two spaces to the end of the first line to introduce a linebreak - this is up to you whether you want to keep it.)

---

Also, thank you for creating this mod! I'm still playing it, having solved the spacecraft puzzle so far, but am having great fun.

**Comment by 2walker2** [comment]
Thanks for letting me know. Just pushed a commit incorporating your fix. Glad you're enjoying the mod.
