### ISSUE TITLE
A discrepancy between first seeing something in-game vs. in the shiplog

### ISSUE THREAD

**Issue by CrypticBird** [2walker2/Astral-Codex#4]
Lingering Chime's entry shows up with a full image of the revealed planet (attached), possibly before the player even sees it in that form for the first time (as it was in my playthrough; I had just gotten to Lingering Chime for the first time and learned its appearance from the shiplog entry, not from actually going through the tesseract).
![20240226181134_1](https://github.com/2walker2/Astral-Codex/assets/99370234/8798b517-21f0-42ac-b65e-3dd2432bc1f9)

**Comment by 2walker2** [comment]
Thanks for letting me know. Should be fixed now.
