### ISSUE TITLE
Error spam in other star systems

### ISSUE THREAD

**Issue by xen-42** [2walker2/Astral-Codex#6]
Fixing would improve mod compatibility, I get this error thrown continuously when I travel to other star systems. Just missing a `nhapi.GetCurrentStarSystem() == "SolarSystem"` check here I presume. 

`NullReferenceException
Stacktrace: AstralCodex.SolarSystemSceneHandler.PreventSkyboxInDreamWorld () (at D:/Code Stuff/REMOTE/Astral-Codex/Scripts/ModTemplate/SolarSystemSceneHandler.cs:622)
AstralCodex.SolarSystemSceneHandler.Update () (at D:/Code Stuff/REMOTE/Astral-Codex/Scripts/ModTemplate/SolarSystemSceneHandler.cs:553)`

**Comment by 2walker2** [comment]
Fixed. Thanks for letting me know about this.
